version: "3"

services:
  apache:
    image: silkrad/apache-php:latest
    build: 
      context: ./dockerfiles/apache
    env_file:
      - ./config/apache.env
    ports:
      - "80:8080"
      - "443:8443"
    volumes: 
      - apache-www:/var/www/
      - apache-log:/var/log/apache2/
      - apache-config:/etc/apache2

volumes:
  apache-www:
  apache-log:
  apache-config: