version: "3"

services:
  apache:
    image: silkrad/apache-php:latest
    build: 
      context: ./src/apache
    env-file:
      - ./config/apache/apache.env
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - apache-www:/var/www/
      - apache-log:/var/log/apache2/
    secrets:
      - source: vhost.cert
        target: /secrets/vhost.cert
      - source: vhost.key
        target: /secrets/vhost.key

secrets:
  vhost.cert:
    file: ./config/apache/vhost.cert
  vhost.key:
    file: ./config/apache/vhost.key

volumes:
  apache-www:
  apache-log: