version: "3.4"

services:
  apache:
    image: silkrad/apache:latest
    build: 
      context: ./src/apache
    env_file:
      - ./config/apache/apache.env
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - apache-www:/var/www/
      - apache-log:/var/log/apache2/
    secrets:
      - source: ca-cert
        target: /run/secrets/ca.cert
      - source: vhost-cert
        target: /run/secrets/vhost.cert
      - source: vhost-key
        target: /run/secrets/vhost.key
  mysql:
    image: silkrad/mysql:latest
    build:
      context: ./src/mysql
    env_file:
      - ./config/mysql/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
    secrets:
      - source: mysql-root
        target: /run/secrets/mysql-root

secrets:
  ca-cert:
    file: ./config/apache/secrets/ca.cert
  vhost-cert:
    file: ./config/apache/secrets/vhost.cert
  vhost-key:
    file: ./config/apache/secrets/vhost.key
  mysql-root:
    file: ./config/mysql/secrets/mysql-root

volumes:
  apache-www:
  apache-log:
  mysql-data:
  mysql-log: